server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "Authorization"

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: election-service
          uri: lb://ELECTION-SERVICE
          predicates:
            - Path=/elections/**

        - id: voting-service
          uri: lb://VOTING-SERVICE
          predicates:
            - Path=/votes/**

        - id: result-service
          uri: lb://RESULT-SERVICE
          predicates:
            - Path=/results/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:civicvote-super-secret-key-that-is-at-least-256-bits-long-for-hs256}
